{{- if .Values.entrypointd }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-entrypointd
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.entrypointd | indent 2 }}
{{- end }}
