{{- if .Values.dindDaemonSet.enabled }}
apiVersion: {{ template "daemonset.apiVersion" . }}
kind: DaemonSet
metadata:
  name: {{ template "name" . }}-dind
  labels:
    app: {{ template "name" . }}-dind
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}-dind
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-dind
    spec:
      initContainers:
        - name: prep
          image: alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: docker-run
            mountPath: /var/buildkite/docker/run
          command:
            - /bin/sh
            - -c
            - rm -f /var/buildkite/docker/run/*.sock
      containers:
      - name: dind
        image: {{ .Values.dindDaemonSet.image }}
        args:
          - "--data-root"
          - "/var/buildkite/docker/storage"
          - "--mtu"
          - "{{ .Values.dindDaemonSet.mtu | default "1450" }}"
{{ toYaml .Values.dindDaemonSet.args | indent 10 }}
        resources:
{{ toYaml .Values.dindDaemonSet.resources | indent 10 }}
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker/docker.sock
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-storage
          mountPath: /var/buildkite/docker
        - name: docker-run
          mountPath: /var/run/docker
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - docker info > /dev/null
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - docker info > /dev/null
          initialDelaySeconds: 5
          periodSeconds: 10          
      volumes:
      - name: docker-storage
        hostPath:
          path: /var/buildkite/docker
          type: DirectoryOrCreate
      - name: docker-run
        hostPath:
          path: /var/buildkite/docker/run
          type: DirectoryOrCreate


{{- end }}