{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ template "pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{- end }}
